export const defaultProcessDocumentTypes = [
  {
    key: 'procuracao_advogado',
    label: 'Procuracao para o advogado',
    sortOrder: 1,
    isRequired: true,
    allowsMultipleFiles: false,
  },
  {
    key: 'rg_cpf_cnh',
    label: 'RG/CPF/CNH',
    sortOrder: 2,
    isRequired: true,
    allowsMultipleFiles: false,
  },
  {
    key: 'comprovante_endereco',
    label: 'Comprovante de endereco',
    sortOrder: 3,
    isRequired: true,
    allowsMultipleFiles: false,
  },
  {
    key: 'termo_entrega_recebimento_imovel',
    label: 'Termo de entrega/recebimento do imovel pela instituicao bancaria',
    sortOrder: 4,
    isRequired: true,
    allowsMultipleFiles: false,
  },
  {
    key: 'declaracao_hipossuficiencia',
    label: 'Declaracao de hipossuficiencia',
    sortOrder: 5,
    isRequired: true,
    allowsMultipleFiles: false,
  },
  {
    key: 'iptu',
    label: 'IPTU',
    sortOrder: 6,
    isRequired: true,
    allowsMultipleFiles: false,
  },
  {
    key: 'solicitacao_caixa',
    label: 'Solicitacao Caixa',
    sortOrder: 7,
    isRequired: true,
    allowsMultipleFiles: false,
  },
  {
    key: 'declaracao_quitacao',
    label: 'Declaracao de quitacao',
    sortOrder: 8,
    isRequired: true,
    allowsMultipleFiles: false,
  },
  {
    key: 'outros',
    label: 'Outros',
    sortOrder: 9,
    isRequired: false,
    allowsMultipleFiles: true,
  },
  {
    key: 'contrato_honorarios_advocaticios',
    label: 'Contrato de honorarios advocaticios',
    sortOrder: 10,
    isRequired: true,
    allowsMultipleFiles: false,
  },
] as const
