/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedSegurancaRouteImport } from './routes/_protected/seguranca'
import { Route as ProtectedProcessosRouteImport } from './routes/_protected/processos'
import { Route as ProtectedPrimeiroAcessoRouteImport } from './routes/_protected/primeiro-acesso'
import { Route as ProtectedConfiguracoesRouteImport } from './routes/_protected/configuracoes'
import { Route as ProtectedCadastrosRouteImport } from './routes/_protected/cadastros'
import { Route as ProtectedTitularesCaixaIndexRouteImport } from './routes/_protected/titulares-caixa.index'
import { Route as ProtectedProcessosIndexRouteImport } from './routes/_protected/processos.index'
import { Route as ProtectedProcessosNovoRouteImport } from './routes/_protected/processos.novo'
import { Route as ProtectedProcessosProcessIdEditarRouteImport } from './routes/_protected/processos.$processId.editar'
import { Route as ProtectedProcessosProcessIdChecklistRouteImport } from './routes/_protected/processos.$processId.checklist'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSegurancaRoute = ProtectedSegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedProcessosRoute = ProtectedProcessosRouteImport.update({
  id: '/processos',
  path: '/processos',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPrimeiroAcessoRoute = ProtectedPrimeiroAcessoRouteImport.update({
  id: '/primeiro-acesso',
  path: '/primeiro-acesso',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedConfiguracoesRoute = ProtectedConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCadastrosRoute = ProtectedCadastrosRouteImport.update({
  id: '/cadastros',
  path: '/cadastros',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTitularesCaixaIndexRoute =
  ProtectedTitularesCaixaIndexRouteImport.update({
    id: '/titulares-caixa/',
    path: '/titulares-caixa/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedProcessosIndexRoute = ProtectedProcessosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedProcessosRoute,
} as any)
const ProtectedProcessosNovoRoute = ProtectedProcessosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => ProtectedProcessosRoute,
} as any)
const ProtectedProcessosProcessIdEditarRoute =
  ProtectedProcessosProcessIdEditarRouteImport.update({
    id: '/$processId/editar',
    path: '/$processId/editar',
    getParentRoute: () => ProtectedProcessosRoute,
  } as any)
const ProtectedProcessosProcessIdChecklistRoute =
  ProtectedProcessosProcessIdChecklistRouteImport.update({
    id: '/$processId/checklist',
    path: '/$processId/checklist',
    getParentRoute: () => ProtectedProcessosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/login': typeof LoginRoute
  '/cadastros': typeof ProtectedCadastrosRoute
  '/configuracoes': typeof ProtectedConfiguracoesRoute
  '/primeiro-acesso': typeof ProtectedPrimeiroAcessoRoute
  '/processos': typeof ProtectedProcessosRouteWithChildren
  '/seguranca': typeof ProtectedSegurancaRoute
  '/processos/novo': typeof ProtectedProcessosNovoRoute
  '/processos/': typeof ProtectedProcessosIndexRoute
  '/titulares-caixa/': typeof ProtectedTitularesCaixaIndexRoute
  '/processos/$processId/checklist': typeof ProtectedProcessosProcessIdChecklistRoute
  '/processos/$processId/editar': typeof ProtectedProcessosProcessIdEditarRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/cadastros': typeof ProtectedCadastrosRoute
  '/configuracoes': typeof ProtectedConfiguracoesRoute
  '/primeiro-acesso': typeof ProtectedPrimeiroAcessoRoute
  '/seguranca': typeof ProtectedSegurancaRoute
  '/': typeof ProtectedIndexRoute
  '/processos/novo': typeof ProtectedProcessosNovoRoute
  '/processos': typeof ProtectedProcessosIndexRoute
  '/titulares-caixa': typeof ProtectedTitularesCaixaIndexRoute
  '/processos/$processId/checklist': typeof ProtectedProcessosProcessIdChecklistRoute
  '/processos/$processId/editar': typeof ProtectedProcessosProcessIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/_protected/cadastros': typeof ProtectedCadastrosRoute
  '/_protected/configuracoes': typeof ProtectedConfiguracoesRoute
  '/_protected/primeiro-acesso': typeof ProtectedPrimeiroAcessoRoute
  '/_protected/processos': typeof ProtectedProcessosRouteWithChildren
  '/_protected/seguranca': typeof ProtectedSegurancaRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/processos/novo': typeof ProtectedProcessosNovoRoute
  '/_protected/processos/': typeof ProtectedProcessosIndexRoute
  '/_protected/titulares-caixa/': typeof ProtectedTitularesCaixaIndexRoute
  '/_protected/processos/$processId/checklist': typeof ProtectedProcessosProcessIdChecklistRoute
  '/_protected/processos/$processId/editar': typeof ProtectedProcessosProcessIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/cadastros'
    | '/configuracoes'
    | '/primeiro-acesso'
    | '/processos'
    | '/seguranca'
    | '/processos/novo'
    | '/processos/'
    | '/titulares-caixa/'
    | '/processos/$processId/checklist'
    | '/processos/$processId/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/cadastros'
    | '/configuracoes'
    | '/primeiro-acesso'
    | '/seguranca'
    | '/'
    | '/processos/novo'
    | '/processos'
    | '/titulares-caixa'
    | '/processos/$processId/checklist'
    | '/processos/$processId/editar'
  id:
    | '__root__'
    | '/_protected'
    | '/login'
    | '/_protected/cadastros'
    | '/_protected/configuracoes'
    | '/_protected/primeiro-acesso'
    | '/_protected/processos'
    | '/_protected/seguranca'
    | '/_protected/'
    | '/_protected/processos/novo'
    | '/_protected/processos/'
    | '/_protected/titulares-caixa/'
    | '/_protected/processos/$processId/checklist'
    | '/_protected/processos/$processId/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/seguranca': {
      id: '/_protected/seguranca'
      path: '/seguranca'
      fullPath: '/seguranca'
      preLoaderRoute: typeof ProtectedSegurancaRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/processos': {
      id: '/_protected/processos'
      path: '/processos'
      fullPath: '/processos'
      preLoaderRoute: typeof ProtectedProcessosRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/primeiro-acesso': {
      id: '/_protected/primeiro-acesso'
      path: '/primeiro-acesso'
      fullPath: '/primeiro-acesso'
      preLoaderRoute: typeof ProtectedPrimeiroAcessoRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/configuracoes': {
      id: '/_protected/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ProtectedConfiguracoesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/cadastros': {
      id: '/_protected/cadastros'
      path: '/cadastros'
      fullPath: '/cadastros'
      preLoaderRoute: typeof ProtectedCadastrosRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/titulares-caixa/': {
      id: '/_protected/titulares-caixa/'
      path: '/titulares-caixa'
      fullPath: '/titulares-caixa/'
      preLoaderRoute: typeof ProtectedTitularesCaixaIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/processos/': {
      id: '/_protected/processos/'
      path: '/'
      fullPath: '/processos/'
      preLoaderRoute: typeof ProtectedProcessosIndexRouteImport
      parentRoute: typeof ProtectedProcessosRoute
    }
    '/_protected/processos/novo': {
      id: '/_protected/processos/novo'
      path: '/novo'
      fullPath: '/processos/novo'
      preLoaderRoute: typeof ProtectedProcessosNovoRouteImport
      parentRoute: typeof ProtectedProcessosRoute
    }
    '/_protected/processos/$processId/editar': {
      id: '/_protected/processos/$processId/editar'
      path: '/$processId/editar'
      fullPath: '/processos/$processId/editar'
      preLoaderRoute: typeof ProtectedProcessosProcessIdEditarRouteImport
      parentRoute: typeof ProtectedProcessosRoute
    }
    '/_protected/processos/$processId/checklist': {
      id: '/_protected/processos/$processId/checklist'
      path: '/$processId/checklist'
      fullPath: '/processos/$processId/checklist'
      preLoaderRoute: typeof ProtectedProcessosProcessIdChecklistRouteImport
      parentRoute: typeof ProtectedProcessosRoute
    }
  }
}

interface ProtectedProcessosRouteChildren {
  ProtectedProcessosNovoRoute: typeof ProtectedProcessosNovoRoute
  ProtectedProcessosIndexRoute: typeof ProtectedProcessosIndexRoute
  ProtectedProcessosProcessIdChecklistRoute: typeof ProtectedProcessosProcessIdChecklistRoute
  ProtectedProcessosProcessIdEditarRoute: typeof ProtectedProcessosProcessIdEditarRoute
}

const ProtectedProcessosRouteChildren: ProtectedProcessosRouteChildren = {
  ProtectedProcessosNovoRoute: ProtectedProcessosNovoRoute,
  ProtectedProcessosIndexRoute: ProtectedProcessosIndexRoute,
  ProtectedProcessosProcessIdChecklistRoute:
    ProtectedProcessosProcessIdChecklistRoute,
  ProtectedProcessosProcessIdEditarRoute:
    ProtectedProcessosProcessIdEditarRoute,
}

const ProtectedProcessosRouteWithChildren =
  ProtectedProcessosRoute._addFileChildren(ProtectedProcessosRouteChildren)

interface ProtectedRouteChildren {
  ProtectedCadastrosRoute: typeof ProtectedCadastrosRoute
  ProtectedConfiguracoesRoute: typeof ProtectedConfiguracoesRoute
  ProtectedPrimeiroAcessoRoute: typeof ProtectedPrimeiroAcessoRoute
  ProtectedProcessosRoute: typeof ProtectedProcessosRouteWithChildren
  ProtectedSegurancaRoute: typeof ProtectedSegurancaRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedTitularesCaixaIndexRoute: typeof ProtectedTitularesCaixaIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedCadastrosRoute: ProtectedCadastrosRoute,
  ProtectedConfiguracoesRoute: ProtectedConfiguracoesRoute,
  ProtectedPrimeiroAcessoRoute: ProtectedPrimeiroAcessoRoute,
  ProtectedProcessosRoute: ProtectedProcessosRouteWithChildren,
  ProtectedSegurancaRoute: ProtectedSegurancaRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedTitularesCaixaIndexRoute: ProtectedTitularesCaixaIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
